# Generated by Django 4.2.11 on 2026-05-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_security_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exportauditlog',
            new_name='accounts_ex_user_id_3b43cc_idx',
            old_name='accounts_ea_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='loginauditlog',
            new_name='accounts_lo_usernam_9ca047_idx',
            old_name='accounts_la_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='loginauditlog',
            new_name='accounts_lo_success_8deef4_idx',
            old_name='accounts_la_succ_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='accounts_us_jti_3b448e_idx',
            old_name='accounts_us_jti_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='accounts_us_user_id_bc9cc2_idx',
            old_name='accounts_us_user_rev_idx',
        ),
    ]
