# Generated by Django 4.2.11 on 2026-05-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organisation_mst_office_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='circle',
            field=models.CharField(blank=True, help_text='Circle/Command name from mst_office', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='close_date',
            field=models.DateField(blank=True, help_text='mst_office.closedate', null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='controlling_office',
            field=models.ForeignKey(blank=True, help_text='mst_office.controllingoffice — administrative controlling authority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_offices', to='accounts.organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='creation_date',
            field=models.DateField(blank=True, help_text='mst_office.creationdate', null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='csum',
            field=models.TextField(blank=True, help_text='Checksum from mst_office'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='display_order',
            field=models.IntegerField(default=0, help_text='mst_office.dorder — sort order within level'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='doe',
            field=models.DateField(blank=True, help_text='Date of Establishment (mst_office.doe)', null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='dou',
            field=models.DateField(blank=True, help_text='Date of last Update (mst_office.dou)', null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='enby',
            field=models.CharField(blank=True, help_text='Entered-by user code from mst_office', max_length=15),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='office_id',
            field=models.CharField(blank=True, help_text='5-character office code from mst_office (e.g. DGDES, PRDSC)', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='office_level_code',
            field=models.CharField(blank=True, help_text='Raw officelevelid from mst_office (e.g. L1, L2)', max_length=2),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='upby',
            field=models.CharField(blank=True, help_text='Updated-by user code from mst_office', max_length=15),
        ),
    ]
