# Generated by Django 4.2.11 on 2026-06-12 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_user_sha512_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gis_layers', '0003_boundary_import_job'),
        ('survey_projects', '0026_rename_survey_proj_feature_a1b2c3_idx_survey_proj_feature_ef939d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuePortalConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label, e.g. "Karnataka Bhoomi WFS"', max_length=200)),
                ('portal_type', models.CharField(choices=[('DILRMP_WFS', 'DILRMP — OGC WFS (NIC GeoServer)'), ('BHUVAN_WFS', 'Bhuvan — OGC WFS (ISRO / NRSC)'), ('BHU_NAKSHA', 'Bhu-Naksha — REST (NIC cadastral maps)'), ('STATE_WFS', 'State Land Portal — OGC WFS'), ('STATE_REST', 'State Land Portal — ArcGIS / REST')], max_length=20)),
                ('base_url', models.URLField(help_text='WFS endpoint, Bhu-Naksha base URL, or ArcGIS service root. Example WFS: https://host/geoserver/wfs  Example ArcGIS: https://host/arcgis/rest/services/Cadastral/FeatureServer/0')),
                ('layer_name', models.CharField(blank=True, help_text='WFS typename (e.g. "revenue:cadastral_plots") or ArcGIS layer ID. Leave blank for Bhu-Naksha (village code drives the query instead).', max_length=300)),
                ('auth_type', models.CharField(choices=[('NONE', 'No authentication'), ('API_KEY', 'API key / token (added as query parameter)'), ('BEARER', 'Bearer token (Authorization header)'), ('BASIC', 'HTTP Basic auth (username + password)')], default='NONE', max_length=10)),
                ('api_key', models.CharField(blank=True, help_text='API key (for API_KEY or BEARER auth types)', max_length=500)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, help_text='Stored in plain text — restrict access to super admins', max_length=200)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Portal-specific options (all optional). WFS: {"version":"1.1.0","max_features":500,"output_format":"application/json"}. Bhu-Naksha: {"state_code":"09","district_code":"01","taluk_code":"","village_code":""}. ArcGIS: {"out_fields":"*","result_record_count":1000}. Field name mappings (for any type): {"survey_number_fields":["plot_no"],"owner_fields":["pattadar_nm"],"area_fields":["area_ha"],"land_type_fields":["land_use"]}. API key query-param name (API_KEY auth): {"api_key_param":"token"}.')),
                ('is_active', models.BooleanField(default=True)),
                ('test_status', models.CharField(choices=[('UNTESTED', 'Not tested yet'), ('OK', 'Connected successfully'), ('ERROR', 'Connection failed')], default='UNTESTED', max_length=10)),
                ('test_message', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_connectors', to='accounts.organisation')),
                ('state', models.ForeignKey(help_text='State whose revenue records this portal serves', on_delete=django.db.models.deletion.PROTECT, related_name='revenue_connectors', to='gis_layers.state')),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParcelRevenueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_survey_number', models.CharField(max_length=200)),
                ('remote_owner', models.CharField(blank=True, max_length=500)),
                ('remote_area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('remote_land_type', models.CharField(blank=True, max_length=300)),
                ('raw_attributes', models.JSONField(default=dict, help_text='All attributes returned by the remote portal')),
                ('overlap_area_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Intersection area between remote parcel and defence parcel (ha)', max_digits=14, null=True)),
                ('overlap_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Overlap as % of the remote parcel area', max_digits=6, null=True)),
                ('discrepancy_flag', models.BooleanField(default=False, help_text='Set when ownership or area conflicts with RakshaGIS records')),
                ('discrepancy_notes', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_links', to='revenue_connectors.revenueportalconnector')),
                ('defence_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_links', to='survey_projects.defenceparcel')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='revenueportalconnector',
            index=models.Index(fields=['organisation', 'is_active'], name='revenue_con_organis_1bd4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueportalconnector',
            index=models.Index(fields=['state', 'portal_type'], name='revenue_con_state_i_453cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelrevenuelink',
            index=models.Index(fields=['defence_parcel', 'connector'], name='revenue_con_defence_6f8cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelrevenuelink',
            index=models.Index(fields=['discrepancy_flag'], name='revenue_con_discrep_03f737_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parcelrevenuelink',
            unique_together={('defence_parcel', 'connector', 'remote_survey_number')},
        ),
    ]
