# Generated by Django 4.2.11 on 2026-05-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0004_alter_externaldatabase_id_alter_externallayer_id'),
        ('external_data', '0005_externallayer_office_filter_field'),
    ]

    operations = [
    ]
