# Generated by Django 4.2.11 on 2026-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0007_externallayer_level_filter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallayer',
            name='office_filter_field',
            field=models.CharField(blank=True, help_text='Fallback column for filtering (used when no per-level override is set). Empty = no filter.', max_length=63),
        ),
    ]
