# Generated by Django 4.2.11 on 2026-06-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0009_externallayer_analysis_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallayer',
            name='classification_colors',
            field=models.JSONField(blank=True, default=dict, help_text='{"A1": {"color": "#1b5e20", "opacity": 0.6}, ...}. Use "__null__" for NULL/empty values.'),
        ),
        migrations.AddField(
            model_name='externallayer',
            name='classification_field',
            field=models.CharField(blank=True, help_text='Attribute column whose unique values drive thematic colours. Empty = flat single-colour style.', max_length=63),
        ),
    ]
