# Generated by Django 4.2.11 on 2026-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0010_externallayer_classification_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallayer',
            name='cantonment_scope',
            field=models.CharField(choices=[('OUTSIDE', 'Outside Cantonment (office hierarchy)'), ('INSIDE', 'Inside Cantonment (CB office codes)')], default='OUTSIDE', help_text='How office filtering resolves the allowed rows.', max_length=10),
        ),
    ]
