# Generated by Django 4.2.11 on 2026-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0011_externallayer_cantonment_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallayer',
            name='inside_render_type',
            field=models.CharField(choices=[('GLR_PLAN', 'GLR Plan (classification colours)'), ('OTHERS', 'Others (single colour)')], default='OTHERS', help_text='Inside-cantonment layers: GLR Plan → classification colouring; Others → flat colour.', max_length=10),
        ),
    ]
