# Generated by Django 4.2.11 on 2026-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0013_gis_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisserverconnection',
            name='base_url',
            field=models.URLField(help_text='Root URL of the GIS server (no trailing slash)', max_length=500),
        ),
        migrations.AlterField(
            model_name='gisserverconnection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gisserverconnection',
            name='token',
            field=models.CharField(blank=True, help_text='Bearer / API key token (used when auth_type=TOKEN)', max_length=500),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='arcgis_query_suffix',
            field=models.CharField(default='/query', help_text='Suffix appended to the layer URL for feature queries', max_length=100),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='bbox',
            field=models.JSONField(blank=True, help_text='[minLon, minLat, maxLon, maxLat] in WGS84', null=True),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='layer_name',
            field=models.CharField(help_text='WMS/WFS type name, WMTS layer name, ArcGIS layer ID, or XYZ URL template', max_length=300),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='wfs_output_fmt',
            field=models.CharField(default='application/json', help_text='WFS outputFormat parameter', max_length=80),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='wms_params',
            field=models.JSONField(blank=True, default=dict, help_text='Extra WMS/WMTS params passed to the tile source (JSON)'),
        ),
        migrations.AlterField(
            model_name='gisserverlayer',
            name='wmts_matrix_set',
            field=models.CharField(blank=True, help_text='WMTS TileMatrixSet identifier (e.g. "EPSG:3857")', max_length=100),
        ),
    ]
