# Generated by Django 4.2.11 on 2026-05-23 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('OSM', 'OpenStreetMap'), ('XYZ', 'Custom XYZ Tiles'), ('WMS', 'WMS Service'), ('WMTS', 'WMTS Service'), ('BING', 'Bing Maps'), ('BHUVAN', 'Bhuvan (ISRO India)')], max_length=10)),
                ('url_template', models.CharField(help_text='Tile URL template, e.g. https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png', max_length=500)),
                ('attribution', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in config — cannot be deleted via API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='basemap_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
