# Generated by Django 4.2.11 on 2026-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brandingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
