# Generated by Django 4.2.11 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_basemapconfig_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_number', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_by', models.CharField(max_length=150)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Provenance Record',
                'verbose_name_plural': 'Provenance Records',
                'ordering': ['-generated_at'],
            },
        ),
    ]
