# Generated by Django 4.2.11 on 2026-06-04 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_provenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('export_type', models.CharField(choices=[('survey_area', 'Survey Area'), ('project', 'Project')], max_length=20)),
                ('object_id', models.IntegerField(db_index=True)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], db_index=True, default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('result_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('progress_msg', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('organisation_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['export_type', 'object_id', 'status'], name='core_export_export__c52154_idx'), models.Index(fields=['organisation_id', 'status'], name='core_export_organis_26ae1f_idx')],
            },
        ),
    ]
