# Generated by Django 4.2.11 on 2026-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_droneupload_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='droneuploadsession',
            new_name='core_droneu_upload__429af6_idx',
            old_name='core_drone_upload_id_idx',
        ),
        migrations.RenameIndex(
            model_name='droneuploadsession',
            new_name='core_droneu_uploade_01ff92_idx',
            old_name='core_drone_user_status_idx',
        ),
        migrations.AlterField(
            model_name='droneuploadsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='droneuploadsession',
            name='total_size',
            field=models.BigIntegerField(help_text='Total file size in bytes'),
        ),
    ]
