# Generated by Django 4.2.11 on 2026-06-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_basemapconfig_arcgis_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemapconfig',
            name='url_template',
            field=models.CharField(blank=True, help_text='Tile URL template. For ARCGIS, enter the MapServer base URL (e.g. https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer).', max_length=500),
        ),
    ]
