# Generated by Django 4.2.11 on 2026-05-23 18:21

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SURVEY_REPORT', 'Survey Report'), ('INSPECTION_REPORT', 'Inspection Report'), ('REVENUE_EXTRACT', 'Revenue Extract'), ('SKETCH', 'Sketch / Drawing'), ('PHOTO', 'Photograph'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('ai_summary', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='documents.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='survey_projects.surveyproject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project', 'category'], name='documents_d_project_d5defc_idx')],
            },
        ),
    ]
