# Generated by Django 4.2.11 on 2026-05-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0013_surveyarea_model'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='survey_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='survey_projects.surveyarea'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='survey_projects.surveyproject'),
        ),
    ]
