# Generated by Django 4.2.11 on 2026-06-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_mapactivitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mapactivitylog',
            new_name='workflow_ma_user_id_cadb82_idx',
            old_name='workflow_map_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='mapactivitylog',
            new_name='workflow_ma_project_503b0f_idx',
            old_name='workflow_map_proj_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='mapactivitylog',
            new_name='workflow_ma_survey__1c3b6c_idx',
            old_name='workflow_map_area_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='mapactivitylog',
            new_name='workflow_ma_action_2196d3_idx',
            old_name='workflow_map_action_ts_idx',
        ),
    ]
