# Generated by Django 4.2.11 on 2026-05-23 18:21

import apps.survey_projects.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gis_layers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=64, validators=[apps.survey_projects.models.validate_layer_name])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('fields', models.JSONField(default=list, help_text='Ordered list of field definition objects (see model docstring).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_templates', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_templates', to='accounts.organisation')),
            ],
            options={
                'ordering': ['layer_name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('survey_type', models.CharField(choices=[('BOUNDARY', 'Boundary Survey'), ('TOPOGRAPHIC', 'Topographic Survey'), ('CANTONMENT', 'Cantonment Survey'), ('REVENUE', 'Revenue Survey'), ('LAYOUT', 'Layout / Sub-division'), ('OTHER', 'Other')], default='BOUNDARY', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Checking'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('RETURNED', 'Returned for Revision')], default='DRAFT', max_length=20)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('total_area_hectares', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.district')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.organisation')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.state')),
                ('taluk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.taluk')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShapefileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.survey_projects.models._shapefile_upload_path)),
                ('layer_name', models.CharField(max_length=64, validators=[apps.survey_projects.models.validate_layer_name])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('feature_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_template', models.ForeignKey(blank=True, help_text='Optional: validate imported attributes against this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='survey_projects.attributetemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shapefile_imports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_imports', to='survey_projects.surveyproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GISFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(blank=True, max_length=50)),
                ('layer_name', models.CharField(max_length=64, validators=[apps.survey_projects.models.validate_layer_name])),
                ('geometry_type', models.CharField(choices=[('POINT', 'Point'), ('LINE', 'Line'), ('POLYGON', 'Polygon')], max_length=10)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('attributes', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_features', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='survey_projects.surveyproject')),
            ],
            options={
                'ordering': ['layer_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DefenceParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CANTONMENT', 'Cantonment'), ('RANGE', 'Firing / Training Range'), ('AIRFIELD', 'Airfield / Helipad'), ('DEPOT', 'Depot / Storehouse'), ('TRAINING_AREA', 'Training Area'), ('HOSPITAL', 'Military Hospital'), ('OFFICE', 'Office / HQ'), ('RESIDENTIAL', 'Residential Colony'), ('OTHER', 'Other')], max_length=20)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('RESTRICTED', 'Restricted'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='UNCLASSIFIED', max_length=15)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('encumbrance_notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gis_layers.district')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='accounts.organisation')),
                ('revenue_maps', models.ManyToManyField(blank=True, related_name='parcels', to='gis_layers.revenuemap')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gis_layers.state')),
                ('survey_project', models.ForeignKey(blank=True, help_text='Most recent survey project that defined this parcel boundary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='survey_projects.surveyproject')),
                ('taluk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.taluk')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_layers.village')),
            ],
            options={
                'ordering': ['parcel_id'],
            },
        ),
        migrations.AddIndex(
            model_name='surveyproject',
            index=models.Index(fields=['status', 'organisation'], name='survey_proj_status_dfecd6_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyproject',
            index=models.Index(fields=['organisation', 'created_at'], name='survey_proj_organis_45488c_idx'),
        ),
        migrations.AddIndex(
            model_name='gisfeature',
            index=models.Index(fields=['project', 'layer_name'], name='survey_proj_project_8b9fec_idx'),
        ),
        migrations.AddIndex(
            model_name='gisfeature',
            index=models.Index(fields=['project', 'is_deleted'], name='survey_proj_project_d1c57e_idx'),
        ),
        migrations.AddIndex(
            model_name='defenceparcel',
            index=models.Index(fields=['organisation', 'category'], name='survey_proj_organis_4e0b67_idx'),
        ),
        migrations.AddIndex(
            model_name='defenceparcel',
            index=models.Index(fields=['state', 'district'], name='survey_proj_state_i_b39799_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributetemplate',
            unique_together={('organisation', 'layer_name')},
        ),
    ]
