# Generated by Django 4.2.11 on 2026-05-24 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_extended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLayerFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('folder_type', models.CharField(choices=[('COMMON', 'Common Layer'), ('BOUNDARY', 'Admin Boundary'), ('PHASE', 'Phase'), ('ZONE', 'Zone'), ('YEAR', 'Year'), ('VERSION', 'Version')], max_length=10)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectshare',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='granted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to='accounts.organisation'),
        ),
        migrations.AddField(
            model_name='projectshare',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='survey_projects.surveyproject'),
        ),
        migrations.AddField(
            model_name='projectlayerfolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectlayerfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey_projects.projectlayerfolder'),
        ),
        migrations.AddField(
            model_name='projectlayerfolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='survey_projects.surveyproject'),
        ),
        migrations.AddField(
            model_name='gisfeature',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='survey_projects.projectlayerfolder'),
        ),
        migrations.AddIndex(
            model_name='gisfeature',
            index=models.Index(fields=['folder', 'is_deleted'], name='survey_proj_folder__9bb4dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectshare',
            unique_together={('project', 'granted_to')},
        ),
    ]
