# Generated by Django 4.2.11 on 2026-05-24 10:33

import apps.survey_projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_projects', '0002_folder_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTiffLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.survey_projects.models._geotiff_upload_path)),
                ('cog_file', models.FileField(blank=True, upload_to=apps.survey_projects.models._geotiff_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('error', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geotiff_layers', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geotiff_layers', to='survey_projects.projectlayerfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geotiff_layers', to='survey_projects.surveyproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
