# Generated by Django 4.2.11 on 2026-05-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0004_attachments_milestones'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmilestone',
            new_name='survey_proj_project_b1855f_idx',
            old_name='survey_proj_proj_due_idx',
        ),
    ]
