# Generated by Django 4.2.11 on 2026-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0006_projectlayerfolder_doc_shapefile_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlayerfolder',
            name='folder_type',
            field=models.CharField(choices=[('COMMON', 'Common Layer'), ('BOUNDARY', 'Admin Boundary'), ('PHASE', 'Phase'), ('ZONE', 'Zone'), ('YEAR', 'Year'), ('VERSION', 'Version'), ('DOC', 'Document Folder'), ('SHAPEFILE', 'GIS / Shapefile Folder')], max_length=10),
        ),
    ]
