# Generated by Django 4.2.11 on 2026-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0009_raster_type_shapefile_folder_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qgisuploadlog',
            new_name='survey_proj_project_5f1076_idx',
            old_name='survey_proj_project_upload_idx',
        ),
        migrations.AlterField(
            model_name='qgisuploadlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
