# Generated by Django 4.2.11 on 2026-05-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0010_others_folder_type'),
        ('survey_projects', '0010_rename_survey_proj_project_upload_idx_survey_proj_project_5f1076_idx_and_more'),
    ]

    operations = [
    ]
