# Generated by Django 4.2.11 on 2026-05-26 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_projects', '0012_shapefileimport_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Checking'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('RETURNED', 'Returned for Revision')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_survey_areas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_areas', to=settings.AUTH_USER_MODEL)),
                ('folder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_area_link', to='survey_projects.projectlayerfolder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_areas', to='survey_projects.surveyproject')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'status'], name='survey_proj_project_5bf053_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
