# Generated by Django 4.2.11 on 2026-05-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_projects', '0013_surveyarea_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file_format', models.CharField(choices=[('kml', 'KML'), ('kmz', 'KMZ'), ('geojson', 'GeoJSON'), ('shapefile', 'Shapefile (ZIP)')], max_length=20)),
                ('file', models.FileField(upload_to='temp_layers/')),
                ('geojson', models.JSONField(blank=True, null=True)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
