# Generated by Django 4.2.11 on 2026-05-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0014_temporarylayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefileimport',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shapefileimport',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
