# Generated by Django 4.2.11 on 2026-05-29 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_rename_accounts_ea_user_ts_idx_accounts_ex_user_id_3b43cc_idx_and_more'),
        ('survey_projects', '0015_shapefile_import_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAreaAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Why access is needed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_access_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('requesting_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_access_requests_sent', to='accounts.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_access_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('survey_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='survey_projects.surveyarea')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('survey_area', 'requesting_org')},
            },
        ),
    ]
