# Generated by Django 4.2.11 on 2026-06-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0018_alter_temporarylayer_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotifflayer',
            name='deo_visible',
            field=models.BooleanField(default=True, help_text='Allow the parent DEO office to view this raster in the Map Viewer.'),
        ),
        migrations.AddField(
            model_name='gisfeature',
            name='deo_visible',
            field=models.BooleanField(default=True, help_text='Allow the parent DEO office to view this feature in the Map Viewer.'),
        ),
        migrations.AddField(
            model_name='shapefileimport',
            name='deo_visible',
            field=models.BooleanField(default=True, help_text='Allow the parent DEO office to view the features imported from this file.'),
        ),
        migrations.AddField(
            model_name='temporarylayer',
            name='deo_visible',
            field=models.BooleanField(default=True, help_text='Allow the parent DEO office to view this temporary layer.'),
        ),
        migrations.AddIndex(
            model_name='gisfeature',
            index=models.Index(fields=['project', 'deo_visible', 'is_deleted'], name='survey_proj_project_2561e4_idx'),
        ),
    ]
