# Generated by Django 4.2.11 on 2026-06-10 09:01

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey_projects', '0022_topologyrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISFeatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_pk', models.IntegerField(db_index=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Created'), ('MODIFY', 'Modified'), ('DELETE', 'Deleted'), ('TRANSFER_OUT', 'Transferred Out'), ('TRANSFER_IN', 'Transferred In')], max_length=15)),
                ('layer_name', models.CharField(blank=True, max_length=64)),
                ('old_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('new_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('old_attributes', models.JSONField(default=dict)),
                ('new_attributes', models.JSONField(default=dict)),
                ('area_status_at_change', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAreaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('WORKFLOW', 'Workflow Transition'), ('SPLIT_BEFORE', 'Before Split'), ('SPLIT_AFTER', 'After Split'), ('TRANSFER', 'Physical Transfer'), ('MANUAL', 'Manual')], default='MANUAL', max_length=15)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('status_at_snapshot', models.CharField(blank=True, max_length=20)),
                ('feature_count', models.IntegerField(default=0)),
                ('features_geojson', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAreaSplitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('SPLIT', 'Area Split'), ('POCKET', 'Pocket Created'), ('TRANSFER', 'Physical Transfer')], max_length=10)),
                ('transferred_feature_ids', models.JSONField(default=list)),
                ('transferred_feature_count', models.IntegerField(default=0)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='gisfeature',
            name='survey_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_features', to='survey_projects.surveyarea'),
        ),
        migrations.AddField(
            model_name='surveyarea',
            name='area_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('POCKET', 'Pocket (sub-area)'), ('SPLIT_RESULT', 'Split Result')], default='STANDARD', max_length=15),
        ),
        migrations.AddField(
            model_name='surveyarea',
            name='parent_area',
            field=models.ForeignKey(blank=True, help_text='Source area this was split or pocketed from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_areas', to='survey_projects.surveyarea'),
        ),
        migrations.AddIndex(
            model_name='gisfeature',
            index=models.Index(fields=['survey_area', 'is_deleted'], name='survey_proj_survey__543923_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyarea',
            index=models.Index(fields=['parent_area'], name='survey_proj_parent__ea0255_idx'),
        ),
        migrations.AddField(
            model_name='surveyareasplitrecord',
            name='new_area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_origin', to='survey_projects.surveyarea'),
        ),
        migrations.AddField(
            model_name='surveyareasplitrecord',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyareasplitrecord',
            name='source_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_events_as_source', to='survey_projects.surveyarea'),
        ),
        migrations.AddField(
            model_name='surveyareasnapshot',
            name='survey_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='survey_projects.surveyarea'),
        ),
        migrations.AddField(
            model_name='surveyareasnapshot',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gisfeaturehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gisfeaturehistory',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='survey_projects.gisfeature'),
        ),
        migrations.AddField(
            model_name='gisfeaturehistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_history', to='survey_projects.surveyproject'),
        ),
        migrations.AddField(
            model_name='gisfeaturehistory',
            name='survey_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_history', to='survey_projects.surveyarea'),
        ),
        migrations.AddIndex(
            model_name='surveyareasnapshot',
            index=models.Index(fields=['survey_area', '-taken_at'], name='survey_proj_survey__94ff7d_idx'),
        ),
        migrations.AddIndex(
            model_name='gisfeaturehistory',
            index=models.Index(fields=['survey_area', '-changed_at'], name='survey_proj_survey__a97448_idx'),
        ),
        migrations.AddIndex(
            model_name='gisfeaturehistory',
            index=models.Index(fields=['project', '-changed_at'], name='survey_proj_project_3eebfa_idx'),
        ),
        migrations.AddIndex(
            model_name='gisfeaturehistory',
            index=models.Index(fields=['survey_area', 'change_type'], name='survey_proj_survey__034ed9_idx'),
        ),
    ]
