# Generated by Django 4.2.11 on 2026-06-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_projects', '0025_featurecomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featurecomment',
            new_name='survey_proj_feature_ef939d_idx',
            old_name='survey_proj_feature_a1b2c3_idx',
        ),
    ]
