# Generated by Django 4.2.11 on 2026-05-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportschedule',
            new_name='reports_rep_is_acti_75ce04_idx',
            old_name='reports_rep_is_acti_idx',
        ),
    ]
