# Generated by Django 4.2.11 on 2026-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_rep_is_acti_idx_reports_rep_is_acti_75ce04_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('STATUS_SUMMARY', 'Project Status Summary'), ('FEATURE_EXPORT', 'Feature Data Export'), ('ACTIVITY_LOG', 'User Activity Log'), ('TERRAIN_SUMMARY', 'Terrain Analysis Summary')], max_length=20),
        ),
    ]
