# Generated by Django 4.2.11 on 2026-05-27 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_assistant', '0002_aitask_gis_indexing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label, e.g. "Local llama3.2"', max_length=100)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai_compat', 'OpenAI-Compatible (LocalAI / LM Studio / LlamaCpp / AnythingLLM)'), ('huggingface', 'HuggingFace Inference API')], default='ollama', max_length=20)),
                ('base_url', models.CharField(help_text='e.g. http://host.docker.internal:11434', max_length=300)),
                ('model_name', models.CharField(help_text='e.g. llama3.2 or meta-llama/Llama-2-7b-chat-hf', max_length=200)),
                ('api_key', models.CharField(blank=True, help_text='API key / Bearer token (leave blank for local servers)', max_length=500)),
                ('timeout', models.PositiveIntegerField(default=120, help_text='Request timeout in seconds')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
