# Generated by Django 4.2.11 on 2026-05-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_folder'),
        ('ai_assistant', '0006_rag_and_vision'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentchunk',
            name='unique_doc_chunk',
        ),
        migrations.AlterField(
            model_name='boundaryextractionjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='boundaryextractionjob',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Existing document record containing the scanned map image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_extractions', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='boundaryextractionjob',
            name='source_image',
            field=models.ImageField(blank=True, help_text='Directly uploaded scanned map image.', null=True, upload_to='boundary_extraction/'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
